criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)criarCartao(
    'Categoria',
    'Pergunta',
    'Resposta'
)